########################################################################
# Service configuration.
#
# This configuration will be overridden by the NODE_ENV profile you use,
# for example development.yml for development profile or production.yml
# for production a so on.
#
########################################################################

service:
  group: SosMedico
  name: UaaService
  version:
    major: 1
    minor: 0
    status: 0   # 0: alpha, 1: beta, 2: release, 3: final

api:
  endpoint:
    port: 5001
    baseRoutingPath: /api/v1
  security:
    enabled: true
    jwt:
      secret: /B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkXp2s5
      expiration:
        enabled: true
        minutes: 13149000

management:
  endpoint:
    port: 5101
    baseRoutingPath: /mgmt
  health:
    path: /health
    full: true

jwt:
  secret: /B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkXp2s5
  expiration:
    enabled: true
    minutes: 13149000

# optional configuration to open a db connection
db:
  client: mysql2
  connection:
    host: localhost
    database: sm_uaa
    user: sm_uaa_usr
    password: sm_uaa_pwd
    charset: utf8
#    timezone: UTC2

elasticsearch:
  host: localhost
  port: 9400
  log:
    type: file
    level: trace
    path: ./logs/elasticsearch

# optional configurtion to open and AMQP connection
amqp:
  url: amqp://sosmmquser:sosmmqpwd@localhost:5672/sosmedico
  exchange:
    name: uaa_events

events:
  mapFile: events-map.json


services:
  api: /api/v1
  user:
    url: http://localhost:5001
    path: /users
  parent:
    url: http://localhost:5002
    path: /parents
  son:
    url: http://localhost:5002
    path: /sons
  pediatrician:
    url: http://localhost:5003
    path: /pediatricians
  addressing:
    url: http://localhost:5004
    path: /addresses

log:
  path: ./logs
  console: true
  level: debug
  json: false
  requests:
    console: true
  errors:
    console: false


# should match your Git repo version
info:
  version: 1.0.0
